services:
  nextjs:
    build:
      context: .
      dockerfile: .docker/dev.Dockerfile
    container_name: jetshift_ui_dev
    ports:
      - "4000:3000"
    volumes:
      - .:/app:delegated
      - /app/node_modules # avoid overwriting with host node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://jetshift:8000/api
      - NEXT_PUBLIC_WS_URL=ws://jetshift:8000/ws/
      - NEXT_PUBLIC_PREFECT_URL=http://jetshift:4200
