import type {Metadata} from "next";
import {Toaster} from "@/components/ui/toaster";
import "../globals.css";
import {Inter} from 'next/font/google';
import {LayoutProvider} from '@/components/providers/layout-provider';
import AppLayout from '@/components/layouts/app-layout'

import {WebSocketProvider} from '@/components/providers/web-socket-provider';
import {getUserFromCookie} from "@/lib/auth-server";

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
});

export const metadata: Metadata = {
    title: "JetShift",
    description: "Generated by create next app",
};

export default async function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    const user = await getUserFromCookie();

    return (
        <html lang="en">
        <body className={`${inter.className}`}>
        <WebSocketProvider>
            <LayoutProvider>
                <AppLayout user={user}>
                    {children}
                </AppLayout>
                <Toaster/>
            </LayoutProvider>
        </WebSocketProvider>
        </body>
        </html>
    );
}
